In [1]:
import numpy as np
import pandas as pd

In [2]:
from boostie.model   import boostieModel
from boostie.data    import (
    make_regression_data,
    make_classification_data,
    make_count_data,
    train_test_split,
)
from boostie.metrics import (
    rmse, mae, r_squared,
    log_loss, accuracy,
    confusion_matrix, precision_recall,
)

## Read Titanic CSV

In [3]:
df_raw = pd.read_csv('./resources/titanic.csv')

In [4]:
df_raw.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Define model

In [5]:
model = boostieModel(
        n_estimators  = 100,
        max_depth     = 3,
        learning_rate = 0.1,
        reg_lambda    = 1.0,
        reg_gamma     = 0.0,
        objective     = "classification",
    )

## Preprocess cols

In [6]:
preproccess={"Embarked": "label_encoder", "Sex": "one_hot_encoding"}

In [7]:
preprocessed_df = model.preprocess(df_raw, feature=preproccess, dropna=False, inplace=False)

In [8]:
preprocessed_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_label_encoded,Sex_male,Sex_female
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S,2,1.0,0.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,0.0,1.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S,2,0.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S,2,0.0,1.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,NaN,S,2,1.0,0.0

## Train Test Split

In [ ]:
TARGET = "Survived"

features = ["SibSp", "Parch", "Fare", "Age"]

In [ ]:
X = df_raw[features].values
y = df_raw[TARGET].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, seed=69)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df_raw[features], df_raw[TARGET], test_size=0.3, seed=69)

## Train

In [ ]:
model.fit(X_train, y_train, verbose=True)

In [ ]:
model.feature_names

## Evaluate

In [ ]:
probs = model.predict(X_test)        # probabilities
print(f"  Log-loss  : {log_loss(y_test, probs):.4f}")
print(f"  Accuracy  : {accuracy(y_test, probs):.4f}")

In [ ]:
cm = confusion_matrix(y_test, probs)
print(f"           pred 0   pred 1")
print(f"  actual 0  {cm[0,0]:>5}    {cm[0,1]:>5}")
print(f"  actual 1  {cm[1,0]:>5}    {cm[1,1]:>5}")

In [ ]:
bins = np.linspace(0, 1, 11)
counts, _ = np.histogram(probs, bins=bins)
for i, c in enumerate(counts):
    lo, hi = bins[i], bins[i+1]
    bar = "▪" * (c // 2)
    print(f"  [{lo:.1f}–{hi:.1f}]  {c:>4}  {bar}")

In [ ]:
importances = model.feature_importances(len(model.feature_names))
for i, imp in enumerate(importances):
    bar = "█" * int(imp * 40)
    print(f"  {model.feature_names[i]}  {imp:.3f}  {bar}")